# Generated by Django 5.2.4 on 2025-09-25 06:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialty', models.CharField(max_length=100)),
                ('is_pediatric', models.BooleanField(default=False)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_first_name', models.CharField(max_length=100)),
                ('patient_last_name', models.CharField(max_length=100)),
                ('patient_age', models.IntegerField(blank=True, null=True)),
                ('patient_gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], default='other', max_length=10)),
                ('reason', models.CharField(blank=True, choices=[('Internal eye examination', 'Internal eye examination'), ('External eye examination', 'External eye examination'), ('Glaucoma Screening', 'Glaucoma Screening'), ('Keratoconus Screening', 'Keratoconus Screening'), ('Vision therapy', 'Vision therapy'), ('Adult and pediatric comprehensive vision', 'Adult and pediatric comprehensive vision'), ('Examination', 'Examination'), ('Binocular vision exam', 'Binocular vision exam'), ('Color vision tests', 'Color vision tests'), ('Myopia management', 'Myopia management'), ('Dry eye test and management', 'Dry eye test and management')], max_length=100, null=True)),
                ('booking_for', models.CharField(choices=[('yourself', 'Yourself'), ('another', 'Another Person')], default='yourself', max_length=20)),
                ('appointment_datetime', models.DateTimeField()),
                ('status', models.CharField(choices=[('Scheduled', 'Scheduled'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Scheduled', max_length=50)),
                ('severity', models.CharField(choices=[('Normal', 'Normal'), ('Requires Attention', 'Requires Attention')], default='Normal', max_length=50)),
                ('archive', models.BooleanField(default=False)),
                ('doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='admin_panel.doctor')),
            ],
        ),
        migrations.CreateModel(
            name='DoctorAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time_slots', models.JSONField(default=list)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_panel.doctor')),
            ],
            options={
                'unique_together': {('doctor', 'date')},
            },
        ),
    ]
