# Generated by Django 5.2.4 on 2025-09-27 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0004_appointment_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='patient_contact',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
