# Generated by Django 5.2.4 on 2025-09-27 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0005_appointment_patient_contact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='patient_contact',
        ),
        migrations.AddField(
            model_name='doctor',
            name='contact_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
