# Generated by Django 5.2.4 on 2025-09-27 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0006_remove_appointment_patient_contact_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='contact_number',
        ),
    ]
