# Generated by Django 5.2.4 on 2025-09-28 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0008_appointment_booker'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='push_token',
            field=models.CharField(blank=True, help_text='Token for sending push notifications (e.g., Firebase/Expo token)', max_length=255, null=True),
        ),
    ]
