# Generated by Django 5.2.6 on 2025-09-30 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0010_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='push_token',
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
