# Generated by Django 5.2.6 on 2025-10-05 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0014_alter_notification_options_notification_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='severity',
        ),
    ]
