# Generated by Django 5.2.6 on 2025-10-05 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0015_remove_appointment_severity'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='severity',
            field=models.CharField(choices=[('Normal', 'Normal'), ('Requires Attention', 'Requires Attention')], default='Normal', max_length=50),
        ),
    ]
