# Generated by Django 5.2.6 on 2025-10-09 23:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0009_appointment_eye_image_appointment_screening_result_and_more'),
        ('admin_panel', '0016_appointment_severity'),
    ]

    operations = [
    ]
