# Generated by Django 5.2.6 on 2025-10-09 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0017_merge_20251010_0744'),
    ]

    operations = [
        migrations.CreateModel(
            name='EyeScreening',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='screening_images/')),
                ('result', models.CharField(max_length=50)),
                ('confidence', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='eye_image',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='screening_result',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='appointment',
        ),
    ]
