# Generated by Django 5.2.6 on 2025-10-13 04:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0019_eyescreening_remarks_eyescreening_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='eye_image',
            field=models.ImageField(blank=True, null=True, upload_to='appointment_screening_images/'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='screening',
            field=models.ForeignKey(blank=True, help_text='Reference to the EyeScreening audit entry, if present.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_appointments', to='admin_panel.eyescreening'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='screening_confidence',
            field=models.FloatField(blank=True, help_text='Confidence in percentage (0-100)', null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='screening_result',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='severity',
            field=models.CharField(choices=[('Normal', 'Strabismus-free'), ('Requires Attention', 'Strabismus')], default='Normal', max_length=50),
        ),
        migrations.AlterField(
            model_name='eyescreening',
            name='confidence',
            field=models.FloatField(help_text='Confidence in percentage (0-100)'),
        ),
    ]
