# Generated by Django 5.2.6 on 2025-10-13 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0020_appointment_eye_image_appointment_screening_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='eye_image',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='screening',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='screening_confidence',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='screening_result',
        ),
        migrations.AlterField(
            model_name='appointment',
            name='severity',
            field=models.CharField(choices=[('Normal', 'Normal'), ('Requires Attention', 'Requires Attention')], default='Normal', max_length=50),
        ),
        migrations.AlterField(
            model_name='eyescreening',
            name='confidence',
            field=models.FloatField(),
        ),
    ]
