# Generated by Django 5.2.6 on 2025-10-23 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0024_loginotp'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LoginOTP',
        ),
    ]
