# Generated by Django 5.2.6 on 2025-10-24 00:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0032_otp'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OTP',
        ),
    ]
