# Generated by Django 5.2.6 on 2025-10-24 04:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0034_userotp'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserOTP',
        ),
    ]
