# Generated by Django 5.2.6 on 2025-10-29 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0048_otp'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OTP',
        ),
    ]
