# Generated by Django 5.2.6 on 2025-10-30 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0053_alter_emailotp_created_at_alter_emailotp_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmailOTP',
        ),
    ]
