# Generated by Django 5.2.6 on 2025-10-30 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0056_remove_appointment_email_remove_appointment_severity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='severity',
            field=models.CharField(choices=[('Normal', 'Normal'), ('Requires Attention', 'Requires Attention')], default='Normal', max_length=50),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='patient_gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female')], default='other', max_length=10),
        ),
    ]
