# Generated by Django 5.2.6 on 2025-10-30 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0057_appointment_severity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='severity',
        ),
    ]
