# Generated by Django 5.2.6 on 2025-10-31 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0059_remove_profile_profile_image_profile_country_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
