# Generated by Django 5.2.6 on 2025-10-31 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0063_adminprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AdminProfile',
        ),
    ]
