# Generated by Django 5.2.6 on 2025-11-02 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0073_remove_appointment_preliminary_result_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='patient_email',
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
    ]
