# Generated by Django 5.2.6 on 2025-11-03 07:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0074_appointment_patient_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='is_ai_screening',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='appointment',
            name='preliminary_result',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='eyescreening',
            name='appointment',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_screening', to='admin_panel.appointment'),
        ),
    ]
