# Generated by Django 5.2.6 on 2025-11-03 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0075_appointment_is_ai_screening_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='is_ai_screening',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='preliminary_result',
        ),
        migrations.RemoveField(
            model_name='eyescreening',
            name='appointment',
        ),
    ]
