# Generated by Django 5.2.6 on 2025-11-04 04:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0078_alter_appointment_preliminary_result'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
