# Generated by Django 5.2.6 on 2025-11-04 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0082_alter_userprofile_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='push_token',
            field=models.CharField(blank=True, help_text='Token for sending push notifications (e.g., Firebase/Expo token).', max_length=255, null=True),
        ),
    ]
