# Generated by Django 5.2.6 on 2025-11-04 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0083_alter_userprofile_push_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='gender',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='push_token',
            field=models.CharField(blank=True, help_text='Token for sending push notifications (e.g., Firebase/Expo token) for patients/general users.', max_length=255, null=True),
        ),
    ]
