# Generated by Django 5.2.6 on 2025-11-04 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0085_userprofile_date_of_birth_userprofile_gender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='push_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
