# Generated by Django 5.2.6 on 2025-11-04 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0086_alter_userprofile_push_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='push_token',
            field=models.CharField(blank=True, help_text='Token for sending push notifications (e.g., Firebase/Expo token).', max_length=255, null=True),
        ),
    ]
