# Generated by Django 5.2.6 on 2025-11-04 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0088_alter_appointment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='is_ai_screening',
            field=models.BooleanField(default=False),
        ),
    ]
