# Generated by Django 5.2.6 on 2025-11-05 01:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0090_activitylog'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ActivityLog',
        ),
    ]
