# Generated by Django 5.2.6 on 2025-11-05 06:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0091_delete_activitylog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
    model_name='eyescreening',
    name='user',
    field=models.ForeignKey(
        on_delete=django.db.models.deletion.CASCADE,
        to='auth.user',
        null=True,
        blank=True,
        related_name='eye_screenings',
    ),
)

    ]
