# Generated by Django 5.2.6 on 2025-11-07 06:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0099_alter_eyescreening_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='eyescreening',
            name='confidence',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='eyescreening',
            name='image',
            field=models.ImageField(upload_to='screening_images/'),
        ),
        migrations.AlterField(
            model_name='eyescreening',
            name='result',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='eyescreening',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='eye_screenings', to=settings.AUTH_USER_MODEL),
        ),
    ]
