# Generated by Django 5.2.6 on 2025-11-08 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0102_alter_eyescreening_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eyescreening',
            name='remarks',
        ),
        migrations.AddField(
            model_name='eyescreening',
            name='diagnosis',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='eyescreening',
            name='confidence',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
