# Generated by Django 5.2.6 on 2025-11-08 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0105_remove_eyescreening_remarks_eyescreening_diagnosis_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eyescreening',
            name='diagnosis',
        ),
        migrations.AddField(
            model_name='eyescreening',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='eyescreening',
            name='confidence',
            field=models.FloatField(),
        ),
    ]
