# Generated by Django 5.2.6 on 2025-11-10 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0109_delete_emailotp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='is_ai_screening',
            field=models.BooleanField(default=True),
        ),
    ]
