# Generated by Django 5.2.6 on 2025-11-30 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0117_alter_appointment_booking_for'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='booking_for',
            field=models.CharField(choices=[('myself', 'Myself'), ('another', 'Another Person')], default='myself', max_length=20),
        ),
    ]
