# Generated by Django 5.2.6 on 2025-12-01 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0124_alter_message_receiver_alter_message_sender_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='receiver',
        ),
        migrations.RemoveField(
            model_name='message',
            name='sender',
        ),
        migrations.DeleteModel(
            name='ChatMessage',
        ),
        migrations.DeleteModel(
            name='Message',
        ),
    ]
