# Generated by Django 5.2.6 on 2025-12-02 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0125_remove_message_receiver_remove_message_sender_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='ai_screening_image_uri',
            field=models.TextField(blank=True, null=True, verbose_name='AI Screening Image URI'),
        ),
    ]
