# Generated by Django 5.2.6 on 2025-12-02 02:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0126_appointment_ai_screening_image_uri'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='ai_screening_image_uri',
        ),
    ]
