# Generated by Django 5.2.6 on 2025-12-02 03:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0127_remove_appointment_ai_screening_image_uri'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='ai_screening_image_uri',
            field=models.TextField(blank=True, null=True, verbose_name='AI Screening Image URI'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='admin_panel.doctor'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='is_ai_screening',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='patient_gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], default='other', max_length=10),
        ),
    ]
