# Generated by Django 5.2.6 on 2025-12-02 03:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0128_appointment_ai_screening_image_uri_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='ai_screening_image_uri',
        ),
        migrations.AlterField(
            model_name='appointment',
            name='doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='admin_panel.doctor'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='is_ai_screening',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='patient_gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female')], default='other', max_length=10),
        ),
    ]
