# Generated by Django 5.2.6 on 2025-12-02 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0129_remove_appointment_ai_screening_image_uri_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='booking_for',
            field=models.CharField(choices=[('myself', 'Myself'), ('another', 'Another Person')], default='myself', max_length=20),
        ),
    ]
