# Generated by Django 5.2.6 on 2025-12-02 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0134_alter_appointment_booking_for'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='booking_for',
            field=models.CharField(choices=[('yourself', 'Yourself'), ('another', 'Another')], default='yourself', max_length=20),
        ),
    ]
